### ISSUE TITLE
zoom in iPad

### ISSUE THREAD

**Issue by paradojaaa** [balaclark/HTML5-Comic-Book-Reader#2]
Making zoom in iPad (with +/-, touching) doesn't work properly

**Comment by balaclark** [comment]
Thanks for the report. This is a known bug and there is a lot to improve for the iPad, but the problem is I don't own one yet so cannot regularly test there at the moment.

**Comment by balaclark** [comment]
I've recently done some mobile optimisations and zoom is now working correctly on the ipad.
