### ISSUE TITLE
Basic example dont work

### ISSUE THREAD

**Issue by Bigua** [balaclark/HTML5-Comic-Book-Reader#6]
The basic example don't work. console error:

GET http://localhost/HTML5-Comic-Book-Reader-master/examples/comicbook/comicbook.css 404 (Not Found) basic.html:14
GET http://localhost/HTML5-Comic-Book-Reader-master/examples/comicbook/js/comicbook.min.js 404 (Not Found) basic.html:13
Uncaught ReferenceError: ComicBook is not defined basic.html:24

I've tried to fix the references,without success.

**Comment by balaclark** [comment]
Did you first build the project (npm install && make)? The compiled files are not saved in git.

**Comment by Bigua** [comment]
Nop, my bad =/, sorry.

Works fine now.
